const apkCommandsData = [
    { id: "apk-update", command: "sudo apk update", keywords: ["index"], technical_desc: "Downloads APKINDEX.tar.gz from repositories into cache.", non_technical_desc: "Refreshes Alpine package index.", example: "sudo apk update", sim_output: "OK: 9984 distinct packages available" },
    { id: "apk-upgrade", command: "sudo apk upgrade", keywords: ["updates"], technical_desc: "Upgrades installed packages if newer versions exist in indexes.", non_technical_desc: "Updates installed packages.", example: "sudo apk upgrade", sim_output: "Upgrading critical operating system libraries...\nOK: 12 MiB in 8 packages" },
    { id: "apk-add", command: "sudo apk add <pkg>", keywords: ["install"], technical_desc: "Resolves constraints with apk-tools SAT solver.", non_technical_desc: "Installs packages.", example: "sudo apk add nginx", sim_output: "(1/3) Installing nginx\nOK: 24 MiB in 42 packages" },
    { id: "apk-del", command: "sudo apk del <pkg>", keywords: ["remove"], technical_desc: "Removes packages and runs uninstall triggers.", non_technical_desc: "Uninstalls packages.", example: "sudo apk del nginx", sim_output: "(1/3) Purging nginx\nOK: 22 MiB in 39 packages" },
    { id: "apk-search", command: "apk search <term>", keywords: ["find"], technical_desc: "Greps repository indexes.", non_technical_desc: "Search package names.", example: "apk search openssh", sim_output: "openssh-9.6_p1-r0\nopenssh-client-common-..." },
    { id: "apk-info", command: "apk info <pkg>", keywords: ["metadata"], technical_desc: "Shows package metadata from index/local.", non_technical_desc: "Package details.", example: "apk info nginx", sim_output: "nginx-1.26.0-r1 description:\nHTTP and reverse proxy server" },
    { id: "apk-info-size", command: "apk info -s <pkg>", keywords: ["installed size"], technical_desc: "Queries database for package file sizing.", non_technical_desc: "Shows how much space an installed package consumes.", example: "apk info -s vim", sim_output: "vim-9.1.0-r0 installed size:\n32 MiB" },
    { id: "apk-policy", command: "apk policy <pkg>", keywords: ["pinning repository policy"], technical_desc: "Displays package version availability matching repositories.", non_technical_desc: "Checks which repository a package version will come from.", example: "apk policy curl", sim_output: "curl policy:\n  8.5.0-r0:\n    lib/apk/db/installed\n    https://dl-cdn.alpinelinux.org/alpine/v3.19/main" },
    { id: "apk-cache-clean", command: "sudo apk cache clean", keywords: ["clean downloads"], technical_desc: "Purges old package archives in the offline caches.", non_technical_desc: "Deletes old downloaded package files from cache.", example: "sudo apk cache clean", sim_output: "" },
    { id: "apk-stats", command: "apk stats", keywords: ["package stats"], technical_desc: "Gathers system statistics from local database catalogs.", non_technical_desc: "Displays system package installation statistics.", example: "apk stats", sim_output: "Installed packages: 250\nInstalled bytes: 320 MiB\nDatabase: 1.2 MiB" },
    { id: "rc-service", command: "rc-service <name> start", keywords: ["openrc"], technical_desc: "OpenRC service manager controls supervise-daemons.", non_technical_desc: "Starts services on Alpine with OpenRC.", example: "sudo rc-service nginx start", sim_output: "* Starting nginx ... [ ok ]" },
];
