const apkLinuxCommandsData = [
    { id: "apk-update", command: "sudo apk update", keywords: ["index"], technical_desc: "Downloads APKINDEX.tar.gz from repositories into cache.", non_technical_desc: "Refreshes Alpine package index.", example: "sudo apk update", sim_output: "OK: 9984 distinct packages available" },
    { id: "apk-upgrade", command: "sudo apk upgrade", keywords: ["updates"], technical_desc: "Upgrades installed packages if newer versions exist in indexes.", non_technical_desc: "Updates installed packages.", example: "sudo apk upgrade", sim_output: "Upgrading critical operating system libraries...\nOK: 12 MiB in 8 packages" },
    { id: "apk-add", command: "sudo apk add <pkg>", keywords: ["install"], technical_desc: "Resolves constraints with apk-tools SAT solver.", non_technical_desc: "Installs packages.", example: "sudo apk add nginx", sim_output: "(1/3) Installing nginx\nOK: 24 MiB in 42 packages" },
    { id: "apk-del", command: "sudo apk del <pkg>", keywords: ["remove"], technical_desc: "Removes packages and runs uninstall triggers.", non_technical_desc: "Uninstalls packages.", example: "sudo apk del nginx", sim_output: "(1/3) Purging nginx\nOK: 22 MiB in 39 packages" },
    { id: "apk-search", command: "apk search <term>", keywords: ["find"], technical_desc: "Greps repository indexes.", non_technical_desc: "Search package names.", example: "apk search openssh", sim_output: "openssh-9.6_p1-r0\nopenssh-client-common-..." },
    { id: "apk-info", command: "apk info <pkg>", keywords: ["metadata"], technical_desc: "Shows package metadata from index/local.", non_technical_desc: "Package details.", example: "apk info nginx", sim_output: "nginx-1.26.0-r1 description:\nHTTP and reverse proxy server" },
    { id: "rc-service", command: "rc-service <name> start", keywords: ["openrc"], technical_desc: "OpenRC service manager controls supervise-daemons.", non_technical_desc: "Starts services on Alpine with OpenRC.", example: "sudo rc-service nginx start", sim_output: "* Starting nginx ... [ ok ]" },
];
