const aptLinuxCommandsData = [
    { id: "apt-update", command: "sudo apt update", keywords: ["refresh", "index", "sources"], technical_desc: "Refreshes local package index files from configured APT repositories without upgrading packages.", non_technical_desc: "Downloads the latest catalog of available software updates.", example: "sudo apt update", sim_output: "Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease\nReading package lists... Done" },
    { id: "apt-upgrade", command: "sudo apt upgrade", keywords: ["install updates"], technical_desc: "Installs newer versions of installed packages respecting pinning and dependency resolution.", non_technical_desc: "Updates installed packages to the newest versions allowed.", example: "sudo apt upgrade", sim_output: "The following packages will be upgraded:\n  curl libcurl4\n2 upgraded, 0 newly installed." },
    { id: "apt-install", command: "sudo apt install <pkg>", keywords: ["add package"], technical_desc: "Resolves dependencies and installs .deb packages plus recommends unless modified.", non_technical_desc: "Installs a program from the repositories.", example: "sudo apt install nginx", sim_output: "The following NEW packages will be installed:\n  nginx\n0 upgraded, 1 newly installed." },
    { id: "apt-remove", command: "sudo apt remove <pkg>", keywords: ["uninstall"], technical_desc: "Removes binaries while leaving configuration files (purge removes configs).", non_technical_desc: "Uninstalls software but may keep settings files.", example: "sudo apt remove apache2", sim_output: "Removing apache2 ..." },
    { id: "apt-autoremove", command: "sudo apt autoremove", keywords: ["cleanup"], technical_desc: "Removes packages installed only as dependencies and no longer required.", non_technical_desc: "Cleans up leftover dependency packages.", example: "sudo apt autoremove", sim_output: "The following packages will be REMOVED:\n  linux-headers-6.5.0-28-generic\n0 upgraded, 0 newly installed, 1 to remove." },
    { id: "apt-search", command: "apt search <name>", keywords: ["find"], technical_desc: "Full-text search across package names and descriptions.", non_technical_desc: "Looks up packages matching a keyword.", example: "apt search ffmpeg", sim_output: "ffmpeg/jammy 7:4.4.2-Oubuntu0.22.04.1 amd64\n  Tools for transcoding..." },
    { id: "dpkg-query", command: "dpkg -l | grep <pkg>", keywords: ["installed"], technical_desc: "dpkg maintains installed package database; -l lists known selections.", non_technical_desc: "Shows whether a package is installed.", example: "dpkg -l | grep nginx", sim_output: "ii  nginx  1.24.0-Oubuntu1 amd64  high performance web server" },
    { id: "systemctl-status", command: "systemctl status <svc>", keywords: ["service", "systemd"], technical_desc: "Queries systemd unit state, PID, cgroup slice, and recent journal lines.", non_technical_desc: "Checks if a background service is running.", example: "systemctl status ssh", sim_output: "● ssh.service - OpenBSD Secure Shell server\n   Active: active (running)" },
    { id: "journalctl", command: "journalctl -u <svc> -e", keywords: ["logs"], technical_desc: "Browses structured journal from systemd-journald.", non_technical_desc: "Reads service logs.", example: "journalctl -u nginx -n 50", sim_output: "... GET / HTTP/1.1\" 200 ..." },
    { id: "hostnamectl", command: "hostnamectl", keywords: ["machine info"], technical_desc: "Shows static/transient hostname and chassis/OS/kernel metadata via systemd-hostnamed.", non_technical_desc: "Shows OS name, kernel, and architecture.", example: "hostnamectl", sim_output: "Operating System: Ubuntu 24.04 LTS\nKernel: Linux 6.8.0-31-generic" },
    { id: "snap-install", command: "sudo snap install <snap>", keywords: ["ubuntu"], technical_desc: "Snap packages are transactional squashfs images refreshed via snapd.", non_technical_desc: "Installs sandboxed apps common on Ubuntu.", example: "sudo snap install code --classic", sim_output: "code 1.xx from Canonical✓ installed" },
    { id: "add-apt-repository", command: "sudo add-apt-repository ppa:...", keywords: ["ppa"], technical_desc: "Adds Launchpad PPA entries to sources.list.d.", non_technical_desc: "Adds a third-party Ubuntu package source.", example: "sudo add-apt-repository ppa:deadsnakes/ppa", sim_output: "PPA publishes deb822 sources ... apt update to refresh." },
];
