const dnfLinuxCommandsData = [
    { id: "dnf-update", command: "sudo dnf check-update", keywords: ["refresh"], technical_desc: "Contacts RPM repositories and lists packages with newer versions.", non_technical_desc: "Shows what could be upgraded without installing yet.", example: "sudo dnf check-update", sim_output: "curl.x86_64    8.5.0-1.fc40    updates" },
    { id: "dnf-upgrade", command: "sudo dnf upgrade", keywords: ["update all"], technical_desc: "Upgrades all packages to latest versions respecting transaction solver.", non_technical_desc: "Updates installed RPM packages.", example: "sudo dnf upgrade", sim_output: "Upgraded:\n curl-8.5.0-1.fc40.x86_64\nComplete!" },
    { id: "dnf-install", command: "sudo dnf install <pkg>", keywords: ["add"], technical_desc: "Resolves RPM dependencies via libsolv and installs.", non_technical_desc: "Installs software from Fedora/RHEL repos.", example: "sudo dnf install git", sim_output: "Installed:\n git-2.45.0-1.fc40.x86_64\nComplete!" },
    { id: "dnf-remove", command: "sudo dnf remove <pkg>", keywords: ["erase"], technical_desc: "Removes package and leaf dependencies when safe.", non_technical_desc: "Uninstalls a package.", example: "sudo dnf remove httpd", sim_output: "Removed:\n httpd-2.4.xx.fc40.x86_64\nComplete!" },
    { id: "dnf-search", command: "dnf search <term>", keywords: ["find"], technical_desc: "Queries repository metadata cache.", non_technical_desc: "Search packages by name/summary.", example: "dnf search podman", sim_output: "podman.x86_64 : Manage pods, containers..." },
    { id: "dnf-repoquery", command: "dnf repoquery -l <pkg>", keywords: ["files"], technical_desc: "RPM query across repos.", non_technical_desc: "Lists files owned by a package.", example: "dnf repoquery -l systemd", sim_output: "/usr/lib/systemd/systemd\n..." },
    { id: "rpm-query", command: "rpm -qa | grep <pkg>", keywords: ["installed"], technical_desc: "Queries RPM database.", non_technical_desc: "Checks installed RPM names.", example: "rpm -qa | grep kernel", sim_output: "kernel-core-6.8.4-200.fc40.x86_64" },
    { id: "systemctl-fedora", command: "systemctl --now enable <svc>", keywords: ["boot"], technical_desc: "Creates symlink in multi-user.target.wants and starts unit.", non_technical_desc: "Turns on a service now and at boot.", example: "sudo systemctl --now enable sshd", sim_output: "Created symlink ... sshd.service ... enabled." },
    { id: "sestatus", command: "sestatus", keywords: ["selinux"], technical_desc: "Shows SELinux enforce mode and policy.", non_technical_desc: "Checks if SELinux is enforcing.", example: "sestatus", sim_output: "SELinux status:                 enabled\nSELinuxfs mount:                /sys/fs/selinux\nCurrent mode:                   enforcing" },
    { id: "subscription-manager", command: "sudo subscription-manager attach --auto", keywords: ["rhel"], technical_desc: "Registers system with RHSM for entitlement pools.", non_technical_desc: "Activates RHEL subscriptions.", example: "sudo subscription-manager attach --auto", sim_output: "Successfully attached a subscription..." },
];
