const emergeLinuxCommandsData = [
    { id: "emerge-sync", command: "sudo emerge --sync", keywords: ["portage tree"], technical_desc: "Updates Portage tree via rsync/git.", non_technical_desc: "Downloads latest Gentoo package tree.", example: "sudo emerge --sync", sim_output: ">>> Syncing repository 'gentoo' into '/usr/portage'...\n... Manifest Timestamp: 2026-05-15" },
    { id: "emerge-world", command: "sudo emerge -uDNav @world", keywords: ["upgrade"], technical_desc: "-u upgrade, -D deep, -N newuse, -av verbose ask.", non_technical_desc: "Smart upgrade of installed packages.", example: "sudo emerge -uDNav @world", sim_output: "These are the packages that would be merged...\n[nomerge]" },
    { id: "emerge-install", command: "sudo emerge <pkg>", keywords: ["install"], technical_desc: "Builds from ebuild with sandbox FEATURES.", non_technical_desc: "Installs by compiling from source (often).", example: "sudo emerge vim", sim_output: ">>> Emerging (1 of 1) app-editors/vim-9.1..." },
    { id: "emerge-info", command: "emerge --info", keywords: ["gentoo system details compiler environment"], technical_desc: "Prints detailed system information including variables from make.conf, gcc version, and USE flags.", non_technical_desc: "Shows detailed compiler environment and compilation options.", example: "emerge --info", sim_output: "Portage 3.0.x (python 3.12.x-default/linux/amd64)\nSystem uname: Linux-6.8-gentoo\nTimestamp of repository gentoo: Sat, 27 Jun 2026..." },
    { id: "emerge-pretend", command: "emerge -p <pkg>", keywords: ["pretend dry run"], technical_desc: "Simulates dependency resolution and compilation steps without making modifications.", non_technical_desc: "Shows what packages will compile and install without doing it yet.", example: "emerge -p nginx", sim_output: "These are the packages that would be merged, in order:\n[ebuild  N     ] www-servers/nginx-1.26.0" },
    { id: "emerge-search", command: "emerge --search <term>", keywords: ["search package"], technical_desc: "Searches the local portage tree package titles.", non_technical_desc: "Searches for packages matching a keyword.", example: "emerge --search firefox", sim_output: "*  www-client/firefox\n      Latest version available: 125.0\n      Description: Firefox Web Browser" },
    { id: "emerge-depclean", command: "sudo emerge --depclean", keywords: ["remove orphans uninstall unused"], technical_desc: "Finds and uninstalls packages installed as dependencies but no longer needed by any world target.", non_technical_desc: "Cleans up unused dependency packages.", example: "sudo emerge --depclean", sim_output: ">>> Calculating dependencies...\n>>> Cleaning packages...\n  app-text/libyaml-0.2.5\n>>> Number of packages: 1" },
    { id: "emerge-unmerge", command: "sudo emerge --unmerge <pkg>", keywords: ["remove"], technical_desc: "Runs uninstall phase hooks.", non_technical_desc: "Removes packages.", example: "sudo emerge --unmerge nginx", sim_output: ">>> Unmerging (1 of 1) www-servers/nginx-1.26..." },
    { id: "eselect-kernel", command: "sudo eselect kernel list", keywords: ["kernel"], technical_desc: "Manages /usr/src/linux symlink alternatives.", non_technical_desc: "Pick active kernel sources.", example: "sudo eselect kernel list", sim_output: "Available kernel symlink targets:\n  [1]   linux-6.8.8-gentoo\n  [2]   linux-6.6.21-gentoo" },
    { id: "dispatch-conf", command: "sudo dispatch-conf", keywords: ["config"], technical_desc: "Interactive merge of cfg-update protected configs.", non_technical_desc: "Resolve config file updates after merges.", example: "sudo dispatch-conf", sim_output: "--- dispatch-conf: processing /etc/group ..." },
];
