const pacmanLinuxCommandsData = [
    { id: "pacman-sync", command: "sudo pacman -Sy", keywords: ["refresh db"], technical_desc: "Synchronizes local sync databases from mirrors.", non_technical_desc: "Updates the package catalog.", example: "sudo pacman -Sy", sim_output: "downloading core.db ...\ndownloading extra.db ..." },
    { id: "pacman-upgrade", command: "sudo pacman -Syu", keywords: ["full upgrade"], technical_desc: "-Syu refreshes DB then upgrades all packages (rolling release core workflow).", non_technical_desc: "Updates everything like a mini distro upgrade.", example: "sudo pacman -Syu", sim_output: ":: Starting full system upgrade...\nresolving dependencies...\nPackages (12) ... Total Download Size:   120 MiB" },
    { id: "pacman-install", command: "sudo pacman -S <pkg>", keywords: ["install"], technical_desc: "Installs packages from sync repos using libalpm.", non_technical_desc: "Installs software.", example: "sudo pacman -S vim", sim_output: "resolving dependencies...\nPackages (1) vim-9.1...\n:: Proceed with installation? [Y/n]" },
    { id: "pacman-remove", command: "sudo pacman -Rns <pkg>", keywords: ["remove"], technical_desc: "-R removes; -n removes config; -s removes unneeded deps.", non_technical_desc: "Uninstalls and cleans dependencies.", example: "sudo pacman -Rns docker", sim_output: "checking dependencies...\nPackages (1) docker ... removed." },
    { id: "pacman-query", command: "pacman -Qs <pkg>", keywords: ["search local"], technical_desc: "Queries local package database.", non_technical_desc: "Search installed packages.", example: "pacman -Qs linux", sim_output: "local/linux 6.8.9.arch1-1\nlocal/linux-headers ..." },
    { id: "pacman-search", command: "pacman -Ss <term>", keywords: ["repos"], technical_desc: "Searches sync databases.", non_technical_desc: "Find packages in repos.", example: "pacman -Ss firefox", sim_output: "extra/firefox 124.0.1-1 Independent web browser" },
    { id: "yay-install", command: "yay -S <pkg>", keywords: ["aur"], technical_desc: "AUR helpers clone PKGBUILD and build with makepkg.", non_technical_desc: "Installs from Arch User Repository.", example: "yay -S google-chrome", sim_output: "AUR Explicit (1): google-chrome...\n==> Making package..." },
    { id: "mkinitcpio", command: "sudo mkinitcpio -P", keywords: ["initramfs"], technical_desc: "Regenerates initramfs images per presets.", non_technical_desc: "Rebuilds boot image after kernel/module changes.", example: "sudo mkinitcpio -P", sim_output: "==> Building image from preset: /etc/mkinitcpio.d/linux.preset" },
];
