const slackwareLinuxCommandsData = [
    { id: "slackpkg-update", command: "sudo slackpkg update", keywords: ["changelog"], technical_desc: "Downloads ChangeLog.txt from mirrors and refreshes package lists.", non_technical_desc: "Refresh Slackware package lists.", example: "sudo slackpkg update", sim_output: "Checking for updates ... DONE\nPackage list updated." },
    { id: "slackpkg-upgrade-all", command: "sudo slackpkg upgrade-all", keywords: ["upgrade"], technical_desc: "Compares installed versions against mirror and prompts upgrades.", non_technical_desc: "Upgrade all packages with confirmations.", example: "sudo slackpkg upgrade-all", sim_output: "The following packages will be upgraded:\n aaa_glibc-solibs ...\nProceed (y/N)?" },
    { id: "slackpkg-install", command: "sudo slackpkg install <pkg>", keywords: ["add"], technical_desc: "Downloads official Slackware packages from mirror.", non_technical_desc: "Install from Slackware sets.", example: "sudo slackpkg install vim", sim_output: "Downloading vim ...\nInstalling vim ... DONE" },
    { id: "slackpkg-remove", command: "sudo slackpkg remove <pkg>", keywords: ["uninstall"], technical_desc: "Runs removepkg.", non_technical_desc: "Remove packages.", example: "sudo slackpkg remove docker", sim_output: "Removing package docker ... DONE" },
    { id: "upgradepkg", command: "sudo upgradepkg <path/to/package.tgz>", keywords: ["manual"], technical_desc: "Upgrades single package from tarball.", non_technical_desc: "Install/upgrade from .tgz on disk.", example: "sudo upgradepkg /tmp/mozilla-firefox-*.txz", sim_output: "Upgrading mozilla-firefox ..." },
    { id: "installpkg", command: "sudo installpkg <path/to/package.tgz>", keywords: ["manual"], technical_desc: "Writes package contents to root.", non_technical_desc: "Install from local .tgz.", example: "sudo installpkg /tmp/foo.tgz", sim_output: "Installing package foo ..." },
    { id: "removepkg", command: "sudo removepkg <pkg>", keywords: ["manual"], technical_desc: "Removes files tracked by package.", non_technical_desc: "Uninstall by package name.", example: "sudo removepkg foo", sim_output: "Removing package /var/log/packages/foo ..." },
];
