const slackwareLinuxCommandsData = [
    { id: "slackpkg-update", command: "sudo slackpkg update", keywords: ["changelog"], technical_desc: "Downloads ChangeLog.txt from mirrors and refreshes package lists.", non_technical_desc: "Refresh Slackware package lists.", example: "sudo slackpkg update", sim_output: "Checking for updates ... DONE\nPackage list updated." },
    { id: "slackpkg-upgrade-all", command: "sudo slackpkg upgrade-all", keywords: ["upgrade"], technical_desc: "Compares installed versions against mirror and prompts upgrades.", non_technical_desc: "Upgrade all packages with confirmations.", example: "sudo slackpkg upgrade-all", sim_output: "The following packages will be upgraded:\n aaa_glibc-solibs ...\nProceed (y/N)?" },
    { id: "slackpkg-install", command: "sudo slackpkg install <pkg>", keywords: ["add"], technical_desc: "Downloads official Slackware packages from mirror.", non_technical_desc: "Install from Slackware sets.", example: "sudo slackpkg install vim", sim_output: "Downloading vim ...\nInstalling vim ... DONE" },
    { id: "slackpkg-remove", command: "sudo slackpkg remove <pkg>", keywords: ["uninstall"], technical_desc: "Runs removepkg.", non_technical_desc: "Remove packages.", example: "sudo slackpkg remove docker", sim_output: "Removing package docker ... DONE" },
    { id: "slackpkg-search", command: "slackpkg search <pkg>", keywords: ["search package mirror"], technical_desc: "Searches for packages matching name in the mirror package list.", non_technical_desc: "Searches for packages in the Slackware mirrors.", example: "slackpkg search firefox", sim_output: "The following packages match your search:\n[installed] - mozilla-firefox-115.8.0es-x86_64-1" },
    { id: "slackpkg-info", command: "slackpkg info <pkg>", keywords: ["package details description info"], technical_desc: "Queries local package catalog for description template metadata.", non_technical_desc: "Shows package description and details from Slackware mirrors.", example: "slackpkg info vim", sim_output: "PACKAGE NAME: vim-9.1.0-x86_64-1.txz\nPACKAGE LOCATION: slackware64/ap\nPACKAGE DESCRIPTION:\nvim (Vi IMproved text editor)" },
    { id: "slackpkg-clean-system", command: "sudo slackpkg clean-system", keywords: ["clean check third party"], technical_desc: "Scans package lists database looking for packages not present in official Slackware mirrors.", non_technical_desc: "Checks and prompts removal of third-party or non-standard packages.", example: "sudo slackpkg clean-system", sim_output: "Looking for third-party packages...\nNo non-official packages found." },
    { id: "slackpkg-new-config", command: "sudo slackpkg new-config", keywords: ["resolve configuration updates"], technical_desc: "Finds .new files in /etc and prompts to merge, keep, or replace them.", non_technical_desc: "Resolves configuration file updates after packages upgrades.", example: "sudo slackpkg new-config", sim_output: "Searching for .new files...\nNo .new files found." },
    { id: "upgradepkg", command: "sudo upgradepkg <path/to/package.tgz>", keywords: ["manual"], technical_desc: "Upgrades single package from tarball.", non_technical_desc: "Install/upgrade from .tgz on disk.", example: "sudo upgradepkg /tmp/mozilla-firefox-*.txz", sim_output: "Upgrading mozilla-firefox ..." },
    { id: "installpkg", command: "sudo installpkg <path/to/package.tgz>", keywords: ["manual"], technical_desc: "Writes package contents to root.", non_technical_desc: "Install from local .tgz.", example: "sudo installpkg /tmp/foo.tgz", sim_output: "Installing package foo ..." },
    { id: "removepkg", command: "sudo removepkg <pkg>", keywords: ["manual"], technical_desc: "Removes files tracked by package.", non_technical_desc: "Uninstall by package name.", example: "sudo removepkg foo", sim_output: "Removing package /var/log/packages/foo ..." },
];
