const xbpsLinuxCommandsData = [
    { id: "xbps-query-remote", command: "sudo xbps-install -Su", keywords: ["upgrade"], technical_desc: "Synchronizes remote repositories and upgrades.", non_technical_desc: "Full system update on Void.", example: "sudo xbps-install -Su", sim_output: "Name    Action Version\n kernel  update 6.8.9_1 ...\nTransaction succeeded." },
    { id: "xbps-install", command: "sudo xbps-install <pkg>", keywords: ["add"], technical_desc: "XBPS installs packages from binary repos.", non_technical_desc: "Install software.", example: "sudo xbps-install nginx", sim_output: "nginx-1.26.0_1: found ...\nnginx-1.26.0_1: unpacking ...\nTransaction succeeded." },
    { id: "xbps-remove", command: "sudo xbps-remove <pkg>", keywords: ["delete"], technical_desc: "Removes package files and updates pkgdb.", non_technical_desc: "Uninstall.", example: "sudo xbps-remove nginx", sim_output: "Removing nginx-1.26.0_1 ...\nTransaction succeeded." },
    { id: "xbps-remove-orphans", command: "sudo xbps-remove -O", keywords: ["remove orphans"], technical_desc: "Cleans up orphaned packages that were installed as dependencies but are no longer required.", non_technical_desc: "Removes unused orphan packages to clean up the system.", example: "sudo xbps-remove -O", sim_output: "Removing orphan: libyaml-0.2.5_1 ... done." },
    { id: "xbps-clean-cache", command: "sudo xbps-remove -o", keywords: ["clean cache packages"], technical_desc: "Removes obsolete cached package files from /var/cache/xbps.", non_technical_desc: "Cleans old package installers from downloads cache.", example: "sudo xbps-remove -o", sim_output: "Cleaning cache repository ... done." },
    { id: "xbps-query", command: "xbps-query -Rs <term>", keywords: ["search"], technical_desc: "Remote search mode.", non_technical_desc: "Search repos.", example: "xbps-query -Rs vim", sim_output: "[*] vim-9.1.x ... Vi IMproved" },
    { id: "xbps-query-info", command: "xbps-query -R <pkg>", keywords: ["package details info"], technical_desc: "Queries repositories for package details.", non_technical_desc: "Shows detailed information about an available package.", example: "xbps-query -R git", sim_output: "pkgname: git\nversion: 2.44.0_1\nshort_desc: Fast, scalable, distributed revision control system" },
    { id: "xbps-query-files", command: "xbps-query -f <pkg>", keywords: ["package files listing"], technical_desc: "Lists files installed by a package in the package database.", non_technical_desc: "Lists all files belonging to an installed package.", example: "xbps-query -f curl", sim_output: "/usr/bin/curl\n/usr/share/man/man1/curl.1" },
    { id: "xbps-alternatives", command: "sudo xbps-alternatives -s <group>", keywords: ["symlinks"], technical_desc: "Manages alternatives groups.", non_technical_desc: "Switch default binary for a group.", example: "sudo xbps-alternatives -s vi", sim_output: "vi -> /usr/bin/vim (selected)" },
    { id: "sv", command: "sudo sv status <svc>", keywords: ["runit"], technical_desc: "Void uses runit by default; sv controls supervise.", non_technical_desc: "Check service status.", example: "sudo sv status sshd", sim_output: "run: sshd: (pid 881) ...; run: log: ..." },
];
