const angularCommandsData = [
    { id: "ng-version", command: "ng version", keywords: ["cli"], technical_desc: "Shows Angular CLI/workspace versions.", non_technical_desc: "Checks Angular toolchain versions.", example: "ng version", sim_output: "Angular CLI: 18.0.0\nAngular: 18.0.0\nNode: 22.2.0" },
    { id: "ng-new", command: "ng new <app>", keywords: ["scaffold"], technical_desc: "Creates workspace with routing/style options.", non_technical_desc: "Creates a new Angular application.", example: "ng new shop --routing --style=scss", sim_output: "CREATE shop/angular.json ...\n✔ Packages installed successfully." },
    { id: "ng-serve", command: "ng serve", keywords: ["dev server"], technical_desc: "Runs webpack/esbuild dev server.", non_technical_desc: "Starts local dev server.", example: "ng serve --open", sim_output: "** Angular Live Development Server **\n✔ Compiled successfully.\nhttp://localhost:4200/" },
    { id: "ng-build", command: "ng build", keywords: ["production"], technical_desc: "Production compilation with budgets.", non_technical_desc: "Builds deployable files.", example: "ng build --configuration production", sim_output: "✔ Browser application bundle generation complete.\ndist/shop/" },
    { id: "ng-test", command: "ng test", keywords: ["karma jasmine"], technical_desc: "Runs unit tests via Karma/Jest.", non_technical_desc: "Runs Angular unit tests.", example: "ng test --watch=false", sim_output: "TOTAL: 24 SUCCESS" },
    { id: "ng-generate-component", command: "ng generate component ui/button", keywords: ["schematics"], technical_desc: "Uses schematics to generate artifacts.", non_technical_desc: "Creates a component folder + files.", example: "ng generate component shared/alert", sim_output: "CREATE src/app/shared/alert/alert.component.ts ..." },
    { id: "ng-generate-service", command: "ng generate service api/user", keywords: ["injectable"], technical_desc: "Creates Injectable service.", non_technical_desc: "Adds a reusable service class.", example: "ng generate service api/auth", sim_output: "CREATE src/app/api/auth/auth.service.ts ..." },
    { id: "ng-add", command: "ng add @angular/material", keywords: ["integrations"], technical_desc: "Runs ng-add schematic.", non_technical_desc: "Adds Angular Material quickly.", example: "ng add @angular/material", sim_output: "Installing packages...\nUPDATE angular.json ..." },
    { id: "ng-update", command: "ng update @angular/core", keywords: ["upgrade"], technical_desc: "Runs migrations across versions.", non_technical_desc: "Updates Angular packages safely.", example: "ng update @angular/core @angular/cli", sim_output: "Using package manager: npm\n** Executing migrations ..." },
    { id: "ng-lint", command: "ng lint", keywords: ["eslint"], technical_desc: "Runs lint builder.", non_technical_desc: "Checks code style.", example: "ng lint", sim_output: "Linting \"shop\"...\nAll files pass linting." },
];
