const apacheCommandsData = [
    { id: "httpd-version", command: "httpd -v", keywords: ["apache"], technical_desc: "Prints Apache version.", non_technical_desc: "Shows Apache version.", example: "httpd -v", sim_output: "Server version: Apache/2.4.58 (Unix)" },
    { id: "apachectl-configtest", command: "apachectl configtest", keywords: ["syntax"], technical_desc: "Parses httpd.conf.", non_technical_desc: "Checks config valid.", example: "apachectl configtest", sim_output: "Syntax OK" },
    { id: "apachectl-graceful", command: "apachectl graceful", keywords: ["reload"], technical_desc: "SIGUSR1 graceful restart.", non_technical_desc: "Reloads config without dropping connections.", example: "sudo apachectl graceful", sim_output: "" },
    { id: "apachectl-restart", command: "apachectl restart", keywords: ["bounce"], technical_desc: "Stop/start workers.", non_technical_desc: "Restarts Apache.", example: "sudo apachectl restart", sim_output: "" },
    { id: "httpd-start", command: "sudo systemctl start httpd", keywords: ["systemd start"], technical_desc: "Starts HTTPD systemd unit.", non_technical_desc: "Starts Apache server.", example: "sudo systemctl start httpd", sim_output: "" },
    { id: "httpd-status", command: "sudo systemctl status httpd", keywords: ["systemd status"], technical_desc: "Queries systemd unit state.", non_technical_desc: "Checks if Apache service is active.", example: "sudo systemctl status httpd", sim_output: "● httpd.service - The Apache HTTP Server\n   Active: active (running) since Sat 2026-06-27..." },
    { id: "apache-modules", command: "httpd -M", keywords: ["modules info"], technical_desc: "Lists compiled-in and shared modules.", non_technical_desc: "Lists all loaded Apache modules.", example: "httpd -M", sim_output: "Loaded Modules:\n core_module (static)\n so_module (static)\n ssl_module (shared)\n rewrite_module (shared)" },
    { id: "apache-status", command: "apachectl status", keywords: ["server-status report"], technical_desc: "Fetches live server status page (requires mod_status).", non_technical_desc: "Displays Apache server load and stats summary.", example: "apachectl status", sim_output: "Apache Server Status for localhost (via 127.0.0.1)\nServer Version: Apache/2.4.58\nServer Load: 0.03 0.05 0.01\nUptime: 2 hours 15 minutes" },
    { id: "htpasswd", command: "htpasswd -c .htpasswd user", keywords: ["basic auth"], technical_desc: "Creates htpasswd file.", non_technical_desc: "Adds password user.", example: "htpasswd -c /etc/httpd/.htpasswd alice", sim_output: "New password:\nRe-type new password:\nAdding password for user alice" },
    { id: "apache-error-log", command: "tail -f /var/log/httpd/error_log", keywords: ["error logs"], technical_desc: "Streams connection/worker errors from system files.", non_technical_desc: "Monitors Apache server error logs in real-time.", example: "tail -n 50 /var/log/httpd/error_log", sim_output: "[authz_core:error] [pid 1502] [client 127.0.0.1:49231] AH01630: client denied by server configuration: /var/www/html/secure" },
];
