const cssCommandsData = [
    { id: "css-concept-padding", command: "padding (CSS)", keywords: ["spacing inside", "box model", "p-", "space"], technical_desc: "Padding expands the area between the element's content edge and its border edge. It absorbs background paints and participates in the CSS box model sizing rules controlled by box-sizing.", non_technical_desc: "Inner breathing room: space inside the border around your text or image.", example: "padding: 12px 24px;", sim_output: "(concept — see visual demo)", visualDemo: "css-padding" },
    { id: "css-concept-margin", command: "margin (CSS)", keywords: ["spacing outside", "m-", "collapse"], technical_desc: "Margin pushes away sibling boxes outside the border edge. Vertical margins between block siblings can collapse to the maximum of the two (CSS 2.1 margin collapsing rules).", non_technical_desc: "Outer air gap between this box and neighboring boxes.", example: "margin: 0 auto;", sim_output: "(concept — see visual demo)", visualDemo: "css-margin" },
    { id: "css-concept-border", command: "border (CSS)", keywords: ["outline", "stroke"], technical_desc: "Border sits between padding and margin in the box model. Width, style, and color map to border-* longhands; affects layout depending on box-sizing.", non_technical_desc: "The visible frame drawn around the padding box.", example: "border: 2px solid #333;", sim_output: "(concept — see visual demo)", visualDemo: "css-border" },
    { id: "css-concept-box-sizing", command: "box-sizing (CSS)", keywords: ["border-box", "content-box", "width"], technical_desc: "content-box makes width apply to content only (border/padding add outside). border-box includes padding and border inside the declared width/height.", non_technical_desc: "Chooses whether padding/border count inside the width you set.", example: "* { box-sizing: border-box; }", sim_output: "(concept — see visual demo)", visualDemo: "css-box-sizing" },
    { id: "css-sass", command: "sass src:dist", keywords: ["scss"], technical_desc: "Dart Sass compiler.", non_technical_desc: "Compiles SCSS to CSS.", example: "sass src/styles:dist/css --style=compressed", sim_output: "Compiled src/styles/main.scss to dist/css/main.css.", visualDemo: "css-padding" },
    { id: "css-postcss", command: "npx postcss input.css -o output.css", keywords: ["autoprefixer"], technical_desc: "PostCSS pipeline transforms.", non_technical_desc: "Adds vendor prefixes and optimizations.", example: "npx postcss styles.css -o bundle.css", sim_output: "" },
    { id: "css-tailwind", command: "npx tailwindcss -i ./src/input.css -o ./dist/output.css", keywords: ["utility", "p-4", "m-4"], technical_desc: "JIT scans templates for utility class names like p-4 (padding) and emits minimal CSS.", non_technical_desc: "Builds utility CSS; spacing utilities map to padding/margin.", example: "npx tailwindcss -i ./src/input.css -o ./dist/output.css --minify", sim_output: "Done in 812ms", visualDemo: "css-padding" },
    { id: "css-stylelint", command: "npx stylelint \"**/*.css\"", keywords: ["lint"], technical_desc: "Lint CSS/SCSS.", non_technical_desc: "Finds CSS mistakes.", example: "npx stylelint \"src/**/*.css\"", sim_output: "✖ 0 problems" },
    { id: "css-lightningcss", command: "npx lightningcss-cli --minify styles.css -o out.css", keywords: ["minify"], technical_desc: "Rust CSS transformer.", non_technical_desc: "Very fast CSS minify/transform.", example: "npx lightningcss-cli --minify styles.css -o out.css", sim_output: "" },
];
