const firebaseCommandsData = [
    { id: "fb-login", command: "firebase login", keywords: ["auth"], technical_desc: "OAuth device login flow.", non_technical_desc: "Logs into Firebase CLI.", example: "firebase login", sim_output: "✔ Firebase CLI Login Successful" },
    { id: "fb-logout", command: "firebase logout", keywords: ["auth logout signout"], technical_desc: "Cleans cached authentication tokens locally.", non_technical_desc: "Logs out of your Firebase account from the CLI.", example: "firebase logout", sim_output: "✔ Logged out from account@example.com" },
    { id: "fb-projects-list", command: "firebase projects:list", keywords: ["list projects metadata"], technical_desc: "Fetches and displays all projects connected to the current account.", non_technical_desc: "Lists all your Firebase projects.", example: "firebase projects:list", sim_output: "┌──────────────────────┬──────────────────────┬─────────────┐\n│ Project Display Name │ Project ID           │ Project Num │\n├──────────────────────┼──────────────────────┼─────────────┤\n│ my-app               │ my-app-123           │ 1234567890  │\n└──────────────────────┴──────────────────────┴─────────────┘" },
    { id: "fb-init", command: "firebase init", keywords: ["scaffold"], technical_desc: "Interactive project setup.", non_technical_desc: "Connects folder to Firebase project.", example: "firebase init hosting", sim_output: "✔ Firebase initialization complete!" },
    { id: "fb-use", command: "firebase use prod", keywords: ["alias"], technical_desc: "Selects project alias.", non_technical_desc: "Switches active Firebase project.", example: "firebase use prod", sim_output: "Now using alias prod (hub-prod)" },
    { id: "fb-emulators", command: "firebase emulators:start", keywords: ["local"], technical_desc: "Starts local emulators.", non_technical_desc: "Runs Firebase locally.", example: "firebase emulators:start", sim_output: "All emulators ready! Hosting Emulator running at http://127.0.0.1:5000" },
    { id: "fb-emulator-export", command: "firebase emulators:export ./data", keywords: ["export data local emulators"], technical_desc: "Saves current state of local database emulators to a directory.", non_technical_desc: "Saves your local database simulator data to a folder.", example: "firebase emulators:export ./data", sim_output: "Export complete. Exported database state to ./data" },
    { id: "fb-emulator-import", command: "firebase emulators:start --import ./data", keywords: ["import data local emulators start"], technical_desc: "Loads database state directory when booting local emulators.", non_technical_desc: "Runs Firebase locally starting with previously saved simulator data.", example: "firebase emulators:start --import ./data", sim_output: "Import complete. Loaded database state from ./data" },
    { id: "fb-deploy", command: "firebase deploy", keywords: ["publish"], technical_desc: "Uploads assets/rules/functions.", non_technical_desc: "Deploys to Firebase.", example: "firebase deploy --only hosting", sim_output: "✔ Deploy complete!\nHosting URL: https://yourapp.web.app" },
    { id: "fb-deploy-firestore", command: "firebase deploy --only firestore", keywords: ["firestore database rules indexes"], technical_desc: "Uploads local security rules (firestore.rules) and indexes (firestore.indexes.json) to project.", non_technical_desc: "Deploys security rules and database indexes for Firestore.", example: "firebase deploy --only firestore", sim_output: "✔  firestore: rules and indexes deployed successfully." },
    { id: "fb-deploy-functions", command: "firebase deploy --only functions", keywords: ["cloud functions"], technical_desc: "Deploys Cloud Functions Gen2.", non_technical_desc: "Uploads serverless functions.", example: "firebase deploy --only functions", sim_output: "✔ functions[api(us-central1)] Successful update operation." },
    { id: "fb-functions-log", command: "firebase functions:log", keywords: ["logs"], technical_desc: "Reads Cloud Logging.", non_technical_desc: "Shows function logs.", example: "firebase functions:log --only api", sim_output: "2026-05-15T12:00:00Z I api: ..." },
];
