const flutterCommandsData = [
    { id: "flutter-doctor", command: "flutter doctor", keywords: ["setup"], technical_desc: "Checks toolchain/SDK licenses.", non_technical_desc: "Verifies Flutter install health.", example: "flutter doctor -v", sim_output: "[✓] Flutter\n[✓] Android toolchain\n[!] Xcode - missing CocoaPods (optional fix)" },
    { id: "flutter-create", command: "flutter create <app>", keywords: ["scaffold"], technical_desc: "Generates lib/, android/, ios/, web/ templates.", non_technical_desc: "Creates new Flutter app.", example: "flutter create shop_app", sim_output: "Creating project shop_app...\n✓ Project ready." },
    { id: "flutter-run", command: "flutter run", keywords: ["device"], technical_desc: "Builds and attaches observatory.", non_technical_desc: "Runs app on connected device.", example: "flutter run -d chrome", sim_output: "Launching lib/main.dart on Chrome...\nFlutter run key commands: r Hot reload." },
    { id: "flutter-build-apk", command: "flutter build apk", keywords: ["android"], technical_desc: "Produces release APK/AAB.", non_technical_desc: "Builds Android package.", example: "flutter build apk --release", sim_output: "✓ Built build/app/outputs/flutter-apk/app-release.apk" },
    { id: "flutter-build-ios", command: "flutter build ipa", keywords: ["ios"], technical_desc: "Creates IPA archive.", non_technical_desc: "Builds iOS archive for App Store.", example: "flutter build ipa", sim_output: "✓ Built build/ios/ipa/App.ipa" },
    { id: "flutter-test", command: "flutter test", keywords: ["unit"], technical_desc: "Runs VM tests.", non_technical_desc: "Runs Flutter tests.", example: "flutter test", sim_output: "00:02 +12: All tests passed!" },
    { id: "flutter-pub-get", command: "flutter pub get", keywords: ["dependencies"], technical_desc: "Resolves pubspec.yaml.", non_technical_desc: "Downloads Dart packages.", example: "flutter pub get", sim_output: "Running pub get...\nGot dependencies!" },
    { id: "dart-fix", command: "dart fix --apply", keywords: ["migrate"], technical_desc: "Applies codemods.", non_technical_desc: "Auto-fixes Dart issues.", example: "dart fix --apply", sim_output: "Computing fixes...\nApplying 5 fixes..." },
];
