const htmlCommandsData = [
    { id: "html-doctype", command: "<!DOCTYPE html>", keywords: ["doctype template root start html5"], technical_desc: "Preamble instruction informing browser engine that document conforms to HTML5 specifications.", non_technical_desc: "Declares that the file is an HTML5 document.", example: "<!DOCTYPE html>\n<html>\n...", sim_output: "" },
    { id: "html-viewport", command: "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">", keywords: ["meta tag viewport responsive scale mobile design screen scaling"], technical_desc: "Instructs layout engine to match client viewport width and configure initial scale levels.", non_technical_desc: "Tells mobile browsers to fit the website scale to the device width.", example: "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">", sim_output: "" },
    { id: "html-stylesheet-link", command: "<link rel=\"stylesheet\" href=\"style.css\">", keywords: ["link styling import stylesheet css file css stylesheet"], technical_desc: "Attaches external style resources to the parser scope.", non_technical_desc: "Links an external CSS file to apply styles to the HTML page.", example: "<link rel=\"stylesheet\" href=\"style.css\">", sim_output: "" },
    { id: "html-script-async", command: "<script async src=\"app.js\"></script>", keywords: ["script execution loading asynchronous js tags downloads async"], technical_desc: "Instructs engine to download scripts in parallel and execute immediately upon completion, bypassing parser blocks.", non_technical_desc: "Downloads JavaScript in the background without freezing the page load.", example: "<script async src=\"app.js\"></script>", sim_output: "" },
    { id: "html-semantic-nav", command: "<nav>\\n  <ul>\\n    <li><a href=\"#\">Home</a></li>\\n  </ul>\\n</nav>", keywords: ["semantic markup containers navigation list items links headers"], technical_desc: "HTML5 semantic element representing a section of navigation links.", non_technical_desc: "Creates a semantic navigation bar template structure.", example: "<nav>\n  <ul>\n    <li><a href=\"#\">Home</a></li>\n  </ul>\n</nav>", sim_output: "" },
    { id: "html-validator-w3c", command: "npx html-validator-cli index.html", keywords: ["lint markup"], technical_desc: "Uses W3C validator API wrapper.", non_technical_desc: "Checks HTML for structural errors.", example: "npx html-validator-cli dist/index.html", sim_output: "✔ Document validates according to chosen schema." },
    { id: "html-prettier", command: "npx prettier -w \"**/*.html\"", keywords: ["format"], technical_desc: "Formats HTML via Prettier printer.", non_technical_desc: "Pretty-prints HTML templates.", example: "npx prettier -w src/index.html", sim_output: "src/index.html 28ms" },
    { id: "html-tidy", command: "tidy -qe index.html", keywords: ["legacy"], technical_desc: "HTML Tidy repairs/markup warnings.", non_technical_desc: "Older CLI to clean messy HTML.", example: "tidy -qe page.html", sim_output: "No warnings or errors." },
    { id: "html-http-serve", command: "python -m http.server", keywords: ["preview"], technical_desc: "Serves static HTML folder.", non_technical_desc: "Opens HTML locally via HTTP.", example: "python -m http.server 8080", sim_output: "Serving HTTP on 0.0.0.0 port 8080" },
    { id: "html-open", command: "start index.html", keywords: ["windows open"], technical_desc: "OS opens default browser.", non_technical_desc: "Opens file in browser (Windows).", example: "start index.html", sim_output: "" },
];
