const jqueryCommandsData = [
    { id: "jq-cdn-script", command: "<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>", keywords: ["cdn script import"], technical_desc: "Imports minified jQuery codebase via official CDN server scripts.", non_technical_desc: "Imports jQuery into your website via HTML script tag.", example: "<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>", sim_output: "" },
    { id: "jq-dom-ready", command: "$(document).ready(function() { ... });", keywords: ["dom ready handler initialization"], technical_desc: "Attaches a listener callback triggered once the HTML document DOM is fully built.", non_technical_desc: "Runs jQuery code only after the page finishes loading.", example: "$(document).ready(function() {\n  console.log('Ready!');\n});", sim_output: "Ready!" },
    { id: "jq-click-event", command: \"$('button').click(function() { ... });\", keywords: ["click event binding listener"], technical_desc: "Binds an event handler callback to the 'click' JavaScript event on selected elements.", non_technical_desc: "Runs code when a button is clicked.", example: "$('button').click(function() {\n  alert('Clicked!');\n});", sim_output: "" },
    { id: "jq-ajax-get", command: "$.get(url, function(data) { ... });", keywords: ["http get ajax request"], technical_desc: "Asynchronous XMLHTTPRequest execution targeting REST endpoints.", non_technical_desc: "Downloads data from an API asynchronously.", example: "$.get('https://api.example.com/data', function(res) {\n  console.log(res);\n});", sim_output: "{ status: 'ok' }" },
    { id: "jq-css-manip", command: "$('#target').css('color', 'red');", keywords: ["style manipulation css"], technical_desc: "Direct inline styling modifier for matching DOM nodes.", non_technical_desc: "Changes elements color or styles instantly.", example: "$('.active-text').css('font-weight', 'bold');", sim_output: "" },
    { id: "jq-npm-install", command: "npm install jquery", keywords: ["cdn alternative"], technical_desc: "Adds jquery package for bundlers.", non_technical_desc: "Installs jQuery locally.", example: "npm install jquery", sim_output: "added 1 package" },
    { id: "jq-bundle-webpack", command: "npm run build", keywords: ["legacy bundle"], technical_desc: "ProvidePlugin injects global $.", non_technical_desc: "Classic pattern for jQuery globals with webpack.", example: "npm run build", sim_output: "chunk vendors.js [jquery]" },
    { id: "jq-eslint-globals", command: "/* global $ */", keywords: ["lint"], technical_desc: "ESLint env/browser globals.", non_technical_desc: "Tell ESLint about `$`.", example: "/* global $, jQuery */", sim_output: "(no console output)" },
    { id: "jq-migrate", command: "npm install jquery-migrate", keywords: ["upgrade"], technical_desc: "Logs deprecated APIs.", non_technical_desc: "Helps upgrading old jQuery code.", example: "npm install jquery-migrate", sim_output: "added jquery-migrate" },
];
