const mongodbCommandsData = [
    { id: "mg-mongosh-connect", command: "mongosh \"mongodb://localhost:27017\"", keywords: ["shell"], technical_desc: "MongoDB Shell connects via topology discovery.", non_technical_desc: "Opens database shell.", example: "mongosh mongodb://localhost:27017/hub", sim_output: "Connecting to: mongodb://localhost:27017/hub\nhub>" },
    { id: "mg-show-dbs", command: "show dbs", keywords: ["list"], technical_desc: "Lists databases by size.", non_technical_desc: "Lists databases.", example: "show dbs", sim_output: "admin   40.00 KiB\nhub    120.00 KiB\nlocal   72.00 KiB" },
    { id: "mg-use", command: "use hub", keywords: ["database"], technical_desc: "Switches db context.", non_technical_desc: "Selects database.", example: "use hub", sim_output: "switched to db hub" },
    { id: "mg-show-collections", command: "show collections", keywords: ["tables"], technical_desc: "Lists collections.", non_technical_desc: "Shows collections.", example: "show collections", sim_output: "users\nsessions" },
    { id: "mg-find", command: "db.users.find()", keywords: ["query"], technical_desc: "Runs find query.", non_technical_desc: "Reads documents.", example: "db.users.find()", sim_output: "{ _id: ObjectId('...'), email: \"you@example.com\" }" },
    { id: "mg-find-filter", command: "db.users.find({ active: true }).limit(5)", keywords: ["query filter"], technical_desc: "Runs find with filter and limit.", non_technical_desc: "Reads matching documents only.", example: "db.users.find({ active: true }).limit(5)", sim_output: "{ _id: ObjectId('...'), email: \"you@example.com\", active: true }" },
    { id: "mg-insertOne", command: "db.users.insertOne({...})", keywords: ["write"], technical_desc: "Inserts single doc.", non_technical_desc: "Adds one document.", example: "db.users.insertOne({ email: \"a@b.com\" })", sim_output: "{ acknowledged: true, insertedId: ObjectId('...') }" },
    { id: "mg-updateOne", command: "db.users.updateOne({...}, {$set:{...}})", keywords: ["modify"], technical_desc: "Updates first match.", non_technical_desc: "Updates documents.", example: "db.users.updateOne({ _id: ObjectId('...') }, { $set:{ active:true }})", sim_output: "{ matchedCount: 1, modifiedCount: 1 }" },
    { id: "mg-deleteMany", command: "db.users.deleteMany({...})", keywords: ["remove"], technical_desc: "Deletes matching docs.", non_technical_desc: "Deletes documents.", example: "db.users.deleteMany({ active:false })", sim_output: "{ acknowledged: true, deletedCount: 12 }" },
    { id: "mg-createIndex", command: "db.users.createIndex({ email: 1 }, { unique: true })", keywords: ["performance"], technical_desc: "Creates index.", non_technical_desc: "Speeds lookups.", example: "db.users.createIndex({ email: 1 }, { unique: true })", sim_output: "email_1" },
    { id: "mg-aggregate", command: "db.orders.aggregate([...])", keywords: ["pipeline"], technical_desc: "Aggregation framework.", non_technical_desc: "Runs analytics pipeline.", example: "db.orders.aggregate([{ $group:{ _id:\"$status\", n:{ $sum:1 } } }])", sim_output: "{ _id: \"paid\", n: 42 }" },
    { id: "mg-tools-mongodump", command: "mongodump --db hub --out ./dump", keywords: ["backup"], technical_desc: "BSON dump utility.", non_technical_desc: "Backs up database files.", example: "mongodump --db hub --out ./dump", sim_output: "done dumping hub.users (120 documents)" },
];
