const mysqlCommandsData = [
    { id: "mysql-connect", command: "mysql -h host -u user -p", keywords: ["login"], technical_desc: "MySQL client using handshake auth.", non_technical_desc: "Opens MySQL shell.", example: "mysql -h 127.0.0.1 -u root -p", sim_output: "Enter password:\nmysql>" },
    { id: "mysql-show-databases", command: "SHOW DATABASES;", keywords: ["list dbs"], technical_desc: "Queries INFORMATION_SCHEMA.", non_technical_desc: "Lists databases.", example: "SHOW DATABASES;", sim_output: "+--------------------+\n| Database           |\n+--------------------+\n| hub                |\n| mysql              |\n+--------------------+" },
    { id: "mysql-use", command: "USE hub;", keywords: ["schema"], technical_desc: "Sets default schema.", non_technical_desc: "Selects database.", example: "USE hub;", sim_output: "Database changed" },
    { id: "mysql-show-tables", command: "SHOW TABLES;", keywords: ["list tables"], technical_desc: "Lists tables in schema.", non_technical_desc: "Shows tables.", example: "SHOW TABLES;", sim_output: "+----------------+\n| Tables_in_hub  |\n+----------------+\n| users          |\n+----------------+" },
    { id: "mysql-describe", command: "DESCRIBE users;", keywords: ["columns"], technical_desc: "Shows column definitions.", non_technical_desc: "Shows table structure.", example: "DESCRIBE users;", sim_output: "| Field | Type        |\n| id    | bigint      |\n| email | varchar(255)|" },
    { id: "mysql-select", command: "SELECT * FROM users LIMIT 5;", keywords: ["query"], technical_desc: "Executes read query.", non_technical_desc: "Reads rows.", example: "SELECT * FROM users LIMIT 5;", sim_output: "| id | email           |\n|  1 | you@example.com |" },
    { id: "mysql-insert", command: "INSERT INTO users VALUES (...);", keywords: ["write"], technical_desc: "Inserts rows.", non_technical_desc: "Adds data.", example: "INSERT INTO users(email) VALUES ('a@b.com');", sim_output: "Query OK, 1 row affected" },
    { id: "mysql-update", command: "UPDATE users SET ...;", keywords: ["modify"], technical_desc: "Updates rows.", non_technical_desc: "Changes existing rows.", example: "UPDATE users SET active=1 WHERE id=1;", sim_output: "Query OK, 1 row affected" },
    { id: "mysql-delete", command: "DELETE FROM users WHERE ...;", keywords: ["remove"], technical_desc: "Deletes rows.", non_technical_desc: "Removes rows.", example: "DELETE FROM users WHERE id=99;", sim_output: "Query OK, 1 row affected" },
    { id: "mysql-explain", command: "EXPLAIN SELECT ...;", keywords: ["performance"], technical_desc: "Shows optimizer plan.", non_technical_desc: "Explains how query runs.", example: "EXPLAIN SELECT * FROM users WHERE email='x';", sim_output: "| type | key | rows |\n| ref  | uniq_email | 1 |" },
    { id: "mysql-mysqldump", command: "mysqldump hub > backup.sql", keywords: ["backup"], technical_desc: "Logical backup streaming SQL.", non_technical_desc: "Exports database to SQL file.", example: "mysqldump -u root hub > hub.sql", sim_output: "-- Dump completed on ..." },
];
