const nginxCommandsData = [
    { id: "ngx-version", command: "nginx -v", keywords: ["version"], technical_desc: "Prints nginx version.", non_technical_desc: "Shows nginx version.", example: "nginx -v", sim_output: "nginx version: nginx/1.24.0" },
    { id: "ngx-test", command: "nginx -t", keywords: ["config"], technical_desc: "Validates configuration.", non_technical_desc: "Checks nginx.conf syntax.", example: "sudo nginx -t", sim_output: "nginx: configuration file /etc/nginx/nginx.conf test is successful" },
    { id: "ngx-reload", command: "nginx -s reload", keywords: ["hot reload"], technical_desc: "Reloads master process.", non_technical_desc: "Reloads config gracefully.", example: "sudo nginx -s reload", sim_output: "" },
    { id: "ngx-stop", command: "nginx -s quit", keywords: ["shutdown"], technical_desc: "Graceful shutdown.", non_technical_desc: "Stops nginx politely.", example: "sudo nginx -s quit", sim_output: "" },
    { id: "ngx-start", command: "sudo systemctl start nginx", keywords: ["systemd start"], technical_desc: "Starts Nginx systemd daemon service.", non_technical_desc: "Starts Nginx server.", example: "sudo systemctl start nginx", sim_output: "" },
    { id: "ngx-status", command: "sudo systemctl status nginx", keywords: ["systemd status"], technical_desc: "Shows active state of systemd unit.", non_technical_desc: "Checks if Nginx is running.", example: "sudo systemctl status nginx", sim_output: "● nginx.service - A high performance web server and a reverse proxy server\n   Active: active (running) since Sat 2026-06-27..." },
    { id: "ngx-custom-conf", command: "nginx -c /etc/nginx/custom.conf", keywords: ["custom configuration"], technical_desc: "Spawns worker instances using custom configuration file.", non_technical_desc: "Starts Nginx with a custom config file.", example: "sudo nginx -c /etc/nginx/custom.conf", sim_output: "" },
    { id: "ngx-access-log", command: "tail -f /var/log/nginx/access.log", keywords: ["logs bash"], technical_desc: "Typical bash monitoring.", non_technical_desc: "Watch requests live (bash).", example: "tail -n 50 /var/log/nginx/access.log", sim_output: "127.0.0.1 - - [15/May/2026:12:00:00 +0000] \"GET / HTTP/1.1\" 200" },
    { id: "ngx-error-log", command: "tail -f /var/log/nginx/error.log", keywords: ["error logs"], technical_desc: "Streams connection/worker errors from system files.", non_technical_desc: "Monitors Nginx server error logs in real-time.", example: "tail -n 50 /var/log/nginx/error.log", sim_output: "2026/06/27 14:10:00 [error] 14022#14022: *1 open() \"/var/www/html/favicon.ico\" failed (2: No such file or directory)" },
    { id: "ngx-help", command: "nginx -h", keywords: ["help CLI options"], technical_desc: "Prints all supported CLI flags.", non_technical_desc: "Displays Nginx CLI help options.", example: "nginx -h", sim_output: "Options:\n  -?,-h         : this help\n  -v            : show version and exit\n  -t            : test configuration and exit" },
];
