const reactCommandsData = [
    { id: "react-create-vite", command: "npm create vite@latest", keywords: ["scaffold"], technical_desc: "Bootstraps Vite-powered SPA selecting React template.", non_technical_desc: "Creates a fast React starter project.", example: "npm create vite@latest my-app -- --template react-ts", sim_output: "Scaffolding project in my-app...\nDone. Now run:\n  cd my-app\n  npm install\n  npm run dev" },
    { id: "react-cra-legacy", command: "npx create-react-app", keywords: ["legacy"], technical_desc: "Older CRA toolchain wrapping webpack.", non_technical_desc: "Classic React starter (mostly legacy vs Vite).", example: "npx create-react-app my-app", sim_output: "Creating a new React app in my-app.\nSuccess!" },
    { id: "react-dev", command: "npm run dev", keywords: ["vite"], technical_desc: "Runs dev server with HMR.", non_technical_desc: "Starts local website with live reload.", example: "npm run dev", sim_output: "  VITE v5.x  ready in 320 ms\n  ➜  Local:   http://localhost:5173/" },
    { id: "react-build", command: "npm run build", keywords: ["production"], technical_desc: "Produces optimized bundles.", non_technical_desc: "Builds files you deploy to hosting.", example: "npm run build", sim_output: "vite v5.x building for production...\ndist/assets/index-*.js  182 kB" },
    { id: "react-preview", command: "npm run preview", keywords: ["serve build"], technical_desc: "Serves production build locally.", non_technical_desc: "Tests the built site locally.", example: "npm run preview", sim_output: "  ➜  Local: http://localhost:4173/" },
    { id: "react-test-vitest", command: "npm run test", keywords: ["vitest"], technical_desc: "Runs Vitest/Jest depending setup.", non_technical_desc: "Runs unit tests.", example: "npm run test -- --run", sim_output: " ✓ src/App.test.tsx (2 tests) 42ms\n Test Files  1 passed" },
    { id: "react-eslint", command: "npx eslint src/", keywords: ["lint"], technical_desc: "eslint react-hooks plugin rules.", non_technical_desc: "Checks React code quality.", example: "npx eslint src/", sim_output: "✖ 0 problems (0 errors, 0 warnings)" },
    { id: "react-storybook", command: "npx storybook@latest init", keywords: ["components"], technical_desc: "Adds Storybook builder.", non_technical_desc: "Creates UI component workshop.", example: "npx storybook@latest init", sim_output: "Storybook initialized.\nnpm run storybook" },
    { id: "react-router-codegen", command: "npm install react-router-dom", keywords: ["routing"], technical_desc: "Adds client-side routing library.", non_technical_desc: "Adds page navigation in SPA.", example: "npm install react-router-dom", sim_output: "added 6 packages" },
];
