const reactnativeCommandsData = [
    { id: "rn-init", command: "npx @react-native-community/cli init", keywords: ["bootstrap"], technical_desc: "Scaffold native RN app with template.", non_technical_desc: "Creates a React Native project.", example: "npx @react-native-community/cli init MyApp", sim_output: "✔ Downloading template\n✔ Installing dependencies\nRun instructions inside MyApp/" },
    { id: "rn-start-metro", command: "npx react-native start", keywords: ["bundler"], technical_desc: "Starts Metro bundler.", non_technical_desc: "Starts JS bundler for devices/simulators.", example: "npx react-native start", sim_output: "Welcome to Metro!\nFast Refresh enabled." },
    { id: "rn-run-ios", command: "npx react-native run-ios", keywords: ["xcode"], technical_desc: "Builds via xcodebuild simulator.", non_technical_desc: "Runs app on iOS simulator.", example: "npx react-native run-ios --simulator \"iPhone 15\"", sim_output: "success Successfully built the app\nLaunching iPhone 15..." },
    { id: "rn-run-android", command: "npx react-native run-android", keywords: ["gradle"], technical_desc: "Invokes Gradle assembleDebug.", non_technical_desc: "Runs app on Android emulator/device.", example: "npx react-native run-android", sim_output: "BUILD SUCCESSFUL\nInstalling APK..." },
    { id: "rn-log-android", command: "npx react-native log-android", keywords: ["logs android trace adb logcat"], technical_desc: "Starts ADB logcat logger filtered by React Native patterns.", non_technical_desc: "Displays Android system and React Native application logs.", example: "npx react-native log-android", sim_output: "Starting logcat...\nI/ReactNative: [Hot Module Replacement] Client ready." },
    { id: "rn-log-ios", command: "npx react-native log-ios", keywords: ["logs ios trace syslog simulator"], technical_desc: "Queries syslog logs from active iOS Simulator boots.", non_technical_desc: "Displays iOS simulator logs for the running application.", example: "npx react-native log-ios", sim_output: "Starting iOS syslog...\n[ReactNative] HMR client ready" },
    { id: "rn-bundle", command: "npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle", keywords: ["manual bundle compilation build assets"], technical_desc: "Manually packages all JS assets into a single static file for offline release builds.", non_technical_desc: "Compiles all JS code manually into a static bundle file for native releases.", example: "npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle", sim_output: "Writing bundle-output to: android/app/src/main/assets/index.android.bundle\nDone!" },
    { id: "expo-start", command: "npx expo start", keywords: ["expo"], technical_desc: "Starts Expo dev tools.", non_technical_desc: "Develop RN with Expo toolkit.", example: "npx expo start", sim_output: "Metro waiting on exp://192.168.1.10:8081\n› Press w │ open web" },
    { id: "expo-install", command: "npx expo install <pkg>", keywords: ["expo install dependencies packages version matching"], technical_desc: "Installs packages targeting versions verified to match the active Expo SDK configuration.", non_technical_desc: "Installs a library with the exact version compatible with your Expo app.", example: "npx expo install react-native-reanimated", sim_output: "Installing 1 SDK-compliant package...\nadded 1 package" },
    { id: "rn-pod-install", command: "cd ios && pod install", keywords: ["cocoapods"], technical_desc: "Resolves iOS pods.", non_technical_desc: "Installs native iOS dependencies.", example: "cd ios && pod install", sim_output: "Pod installation complete! 42 pods installed" },
    { id: "rn-clean", command: "watchman watch-del-all && rm -rf node_modules && npm install", keywords: ["clean reset reload delete caches npm reinstall"], technical_desc: "Resets file monitoring indices and force reinstalls all workspace dependencies.", non_technical_desc: "Completely cleans cache, deletes downloads, and reinstalls libraries to resolve build conflicts.", example: "watchman watch-del-all && rm -rf node_modules && npm install", sim_output: "All watchman watches deleted.\nadded 512 packages" },
];
