const svelteCommandsData = [
    { id: "sv-create", command: "npm create svelte@latest", keywords: ["kit scaffold"], technical_desc: "Bootstraps SvelteKit/Vite options.", non_technical_desc: "Creates a Svelte project.", example: "npm create svelte@latest my-app", sim_output: "✔ Project created\r\nnpm install && npm run dev -- --open" },
    { id: "sv-create-vite", command: "npm create vite@latest my-app -- --template svelte-ts", keywords: ["vite scaffold svelte"], technical_desc: "Bootstraps a pure client-side Svelte Single Page Application with TypeScript using Vite.", non_technical_desc: "Creates a fast client-only Svelte template project with Vite.", example: "npm create vite@latest my-app -- --template svelte-ts", sim_output: "Scaffolding project in my-app...\nDone. Now run:\n  cd my-app\n  npm install\n  npm run dev" },
    { id: "sv-dev", command: "npm run dev", keywords: ["vite"], technical_desc: "Runs dev server.", non_technical_desc: "Starts local dev.", example: "npm run dev", sim_output: "  ➜ Local: http://localhost:5173/" },
    { id: "sv-build", command: "npm run build", keywords: ["adapter"], technical_desc: "Builds SSR/edge bundles per adapter.", non_technical_desc: "Creates production build.", example: "npm run build", sim_output: "✓ built in 6.02s\n.svelte-kit/output" },
    { id: "sv-preview", command: "npm run preview", keywords: ["serve"], technical_desc: "Runs preview server against build.", non_technical_desc: "Tests production output.", example: "npm run preview", sim_output: "Listening on http://localhost:4173" },
    { id: "sv-check", command: "npm run check", keywords: ["types"], technical_desc: "Runs svelte-check.", non_technical_desc: "Validates components/types.", example: "npm run check", sim_output: "svelte-check found 0 errors and 0 warnings" },
    { id: "sv-add-tailwind", command: "npx svelte-add@latest tailwindcss", keywords: ["add tailwind css styling"], technical_desc: "Svelte-add utility script modifies tailwind.config and app.postcss integrations.", non_technical_desc: "Adds Tailwind CSS to your Svelte project automatically.", example: "npx svelte-add@latest tailwindcss", sim_output: "Writing tailwind.config.js...\nWriting src/app.postcss...\nDone!" },
    { id: "sv-format", command: "npx prettier --write --plugin prettier-plugin-svelte .", keywords: ["prettify code formatting"], technical_desc: "Invokes prettier parser loading specialized .svelte template document formatter plugins.", non_technical_desc: "Auto-formats all .svelte and JS files.", example: "npx prettier --write --plugin prettier-plugin-svelte .", sim_output: "src/routes/+page.svelte 120ms\nsrc/lib/Header.svelte 42ms" },
    { id: "sv-add-routing", command: "npm install svelte-routing", keywords: ["install routing client"], technical_desc: "Installs declarative client routing package dependencies.", non_technical_desc: "Installs Svelte routing library for multi-page SPA navigation.", example: "npm install svelte-routing", sim_output: "added 4 packages in 2.1s" },
    { id: "sv-test-unit", command: "npm run test:unit", keywords: ["unit tests vitest"], technical_desc: "Runs Vitest test runner targeting component specs.", non_technical_desc: "Runs Svelte component unit tests.", example: "npm run test:unit", sim_output: "✓ src/lib/Counter.test.ts (1 test) 20ms\nTest Files: 1 passed" },
];
