const typescriptCommandsData = [
    { id: "ts-version", command: "tsc --version", keywords: ["compiler"], technical_desc: "Prints TypeScript compiler version.", non_technical_desc: "Checks installed TypeScript.", example: "tsc --version", sim_output: "Version 5.4.5" },
    { id: "ts-init", command: "tsc --init", keywords: ["tsconfig"], technical_desc: "Writes tsconfig.json scaffold.", non_technical_desc: "Creates TypeScript config.", example: "tsc --init", sim_output: "Created tsconfig.json" },
    { id: "ts-compile", command: "tsc", keywords: ["build"], technical_desc: "Compiles project per tsconfig.", non_technical_desc: "Turns TS into JS files.", example: "tsc -p .", sim_output: "" },
    { id: "ts-target", command: "tsc --target es2022 src/index.ts", keywords: ["transpile target"], technical_desc: "Transpiles TypeScript targeting specific ECMAScript version.", non_technical_desc: "Compiles a file to a specific JavaScript version (like ES2022).", example: "tsc --target es2022 src/index.ts", sim_output: "" },
    { id: "ts-noEmit", command: "tsc --noEmit", keywords: ["ci"], technical_desc: "Typecheck only.", non_technical_desc: "Checks types without writing files.", example: "tsc --noEmit", sim_output: "" },
    { id: "ts-check-fast", command: "tsc --noEmit --skipLibCheck", keywords: ["fast typecheck"], technical_desc: "Performs compiler typecheck bypassing parsing of .d.ts library files.", non_technical_desc: "Type-checks your code fast, skipping external libraries.", example: "tsc --noEmit --skipLibCheck", sim_output: "" },
    { id: "ts-declarations", command: "tsc --declaration --emitDeclarationOnly", keywords: ["d.ts emit"], technical_desc: "Generates only .d.ts declaration definitions, bypassing JS output.", non_technical_desc: "Generates type definition files (.d.ts) only.", example: "tsc --declaration --emitDeclarationOnly", sim_output: "" },
    { id: "ts-watch", command: "tsc --watch", keywords: ["watch"], technical_desc: "Incremental watch mode.", non_technical_desc: "Rebuilds on save.", example: "tsc --watch", sim_output: "[12:01:02 AM] Starting compilation in watch mode...\n[12:01:03 AM] Found 0 errors." },
    { id: "ts-show-config", command: "tsc --showConfig", keywords: ["tsconfig diagnostic"], technical_desc: "Prints the fully resolved compiler options from current config.", non_technical_desc: "Shows your parsed TypeScript config file options resolved.", example: "tsc --showConfig", sim_output: "{\n  \"compilerOptions\": {\n    \"target\": \"es2022\",\n    \"module\": \"commonjs\"\n  }\n}" },
    { id: "ts-explain-files", command: "tsc --explainFiles", keywords: ["debug compiler"], technical_desc: "Lists all files parsed and details the reason for their inclusion.", non_technical_desc: "Explains why specific files were included in the compilation.", example: "tsc --explainFiles", sim_output: "node_modules/typescript/lib/lib.es5.d.ts\n  Library referenced via default library\nsrc/index.ts\n  Matched by include pattern" },
    { id: "ts-node", command: "ts-node src/main.ts", keywords: ["runtime"], technical_desc: "Runs TS via transpile hooks.", non_technical_desc: "Runs TypeScript directly.", example: "ts-node src/main.ts", sim_output: "Server listening on 4000" },
    { id: "tsx-run", command: "npx tsx watch src/index.ts", keywords: ["esbuild"], technical_desc: "esbuild-powered TS runner.", non_technical_desc: "Fast TS execution alternative.", example: "npx tsx src/index.ts", sim_output: "done" },
];
