const vuejsCommandsData = [
    { id: "vue-create", command: "npm create vue@latest", keywords: ["vite scaffold"], technical_desc: "Official Vue starter using create-vue templates.", non_technical_desc: "Creates a Vue 3 project.", example: "npm create vue@latest my-vue-app", sim_output: "✔ Project scaffolding complete.\ncd my-vue-app && npm install && npm run dev" },
    { id: "vue-create-vite", command: "npm create vite@latest my-app -- --template vue-ts", keywords: ["vite scaffold vue"], technical_desc: "Bootstraps a lightweight client-side Vue Single Page Application with TypeScript using Vite.", non_technical_desc: "Creates a fast client-only Vue template project with Vite.", example: "npm create vite@latest my-app -- --template vue-ts", sim_output: "Scaffolding project in my-app...\nDone. Now run:\n  cd my-app\n  npm install\n  npm run dev" },
    { id: "vue-dev", command: "npm run dev", keywords: ["vite"], technical_desc: "Starts Vite dev server.", non_technical_desc: "Runs local dev with HMR.", example: "npm run dev", sim_output: "  VITE v5.x ready\n  ➜ http://localhost:5173/" },
    { id: "vue-build", command: "npm run build", keywords: ["bundle"], technical_desc: "Produces production assets.", non_technical_desc: "Builds site for deployment.", example: "npm run build", sim_output: "✓ built in 4.21s\ndist/index.html" },
    { id: "vue-preview", command: "npm run preview", keywords: ["serve"], technical_desc: "Serves dist preview.", non_technical_desc: "Tests production build locally.", example: "npm run preview", sim_output: "  ➜ Local: http://localhost:4173/" },
    { id: "vue-typecheck", command: "npx vue-tsc --noEmit", keywords: ["typecheck vue typescript"], technical_desc: "Runs TypeScript compiler with vue-tsc compiler extension to typecheck Single File Components (.vue).", non_technical_desc: "Checks types in Vue templates and scripts.", example: "npx vue-tsc --noEmit", sim_output: "Found 0 errors." },
    { id: "vue-devtools", command: "npx vue-devtools", keywords: ["inspect debugging"], technical_desc: "Launches standalone Vue DevTools window for inspecting component states.", non_technical_desc: "Opens the standalone debugger tool for Vue.", example: "npx vue-devtools", sim_output: "Vue Devtools Server running on http://localhost:8098" },
    { id: "vue-test-vitest", command: "npm run test:unit", keywords: ["vitest"], technical_desc: "Runs Vitest suite.", non_technical_desc: "Runs Vue unit tests.", example: "npm run test:unit -- --run", sim_output: " ✓ tests passed (5)" },
    { id: "vue-test-e2e", command: "npm run test:e2e", keywords: ["playwright cypress e2e"], technical_desc: "Launches end-to-end automated testing runner configured in the workspace.", non_technical_desc: "Runs browser end-to-end tests for the Vue app.", example: "npm run test:e2e", sim_output: "Running 3 test files... Passed!" },
    { id: "vue-add-router", command: "npm install vue-router@4", keywords: ["spa"], technical_desc: "Adds official router.", non_technical_desc: "Adds multi-page navigation.", example: "npm install vue-router@4", sim_output: "added 3 packages" },
    { id: "vue-add-pinia", command: "npm install pinia", keywords: ["state"], technical_desc: "Adds Pinia store.", non_technical_desc: "Adds global state management.", example: "npm install pinia", sim_output: "added 2 packages" },
];
